name: mypy

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies table_extraction
        run: poetry install --with dev,table_extraction --no-interaction --no-root

      - name: Run mypy table_extraction
        run: poetry run mypy table_extraction

      - name: Install dependencies geocoding
        run: poetry install --with dev,geocoding --no-interaction --no-root

      - name: Run mypy geocoding
        run: poetry run mypy geocoding

