name: pytest

"on":
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_CI_TESTDATA_ROOT: "data/test_data"

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Pull required LFS fixtures
        run: git lfs pull --include="data/test_data" --include="data/auxiliary" --exclude=""  

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies table_extraction
        if: ${{ always() }}
        run: poetry install --with dev,table_extraction --no-interaction --no-root

      - name: Run pytest table_extraction
        run: poetry run pytest table_extraction

      - name: Install dependencies geocoding
        if: ${{ always() }}
        run: poetry install --with dev,geocoding --no-interaction --no-root

      - name: Run pytest geocoding
        run: poetry run pytest geocoding
